### ISSUE TITLE
Cannot convert value of type 'Data?' to expected argument type '<<error type>>'

### ISSUE THREAD

**Issue by celosotomaior** [tjeerdintveen/manning-swift-in-depth#4]
I'm having issue when I try to compile the FourSquare API implementation, ErrorHandling, exercises 1, 2,3, 4 and 5.

```
let result = Result<Data, FourSquareError>(value: data, error: translatedError)
> Error: Cannot convert value of type 'Data?' to expected argument type '<<error type>>'
```

```
extension Result {
    
    /// Evaluates the given closure when this Result instance has a value.
    public func mapError<E: Error>(_ transform: (ErrorType) throws -> E) rethrows -> Result<Value, E> {
        switch self {
        case .success(let value):
            return Result<Value, E>(value)
        case .failure(let error):
            return Result<Value, E>(try transform(error))
        }
    }
}
> Errors: Use of undeclared type 'ErrorType', Use of undeclared type 'Value'
```

What's the problem? I'm running the XCode v.11.4 

Lastly but not least, this line below isn't correct, right?
```
completion(Result(.couldNotCreateURL))
```
Shouldn't it be:
```
completion(Result.failure(.couldNotCreateURL)) ?
```

Thanks in advance.

Marcelo

**Comment by tjeerdintveen** [comment]
Hi

I think this is because this is using the Swift 4.2 exercise with an Xcode that supprts Swift 5.

There’s a free Swift 5 ebook update, also the code has been updated. I recommend pulling the latest code and get the book update and all should be good again 👍

**Comment by celosotomaior** [comment]
Hi Tjeerd,

Thank you for letting me know. It makes sense. The new version is working perfectly. 👌

Your book is amazing by the way. 👍

**Comment by tjeerdintveen** [comment]
Great, good to hear that solved it. And I am happy you like it so much. Thanks for letting me know!

Can I ask for an amazon review if it isn’t too much trouble?

**Comment by celosotomaior** [comment]
Sure thing. I did the review on Amazon UK, where I bought it.

**Comment by tjeerdintveen** [comment]
Thanks a lot!

Okay I think I can close this issue since you can continue again. Happy programming! :-)
