### ISSUE TITLE
Thanks a lot!

### ISSUE THREAD

**Issue by celosotomaior** [tjeerdintveen/manning-swift-in-depth#5]
Thanks a lot!

Okay I think I can close this issue since you can continue again. Happy programming! :-)

_Originally posted by @tjeerdintveen in https://github.com/tjeerdintveen/manning-swift-in-depth/issues/4#issuecomment-610160308_

**Comment by celosotomaior** [comment]
Hi Tjeerd,

I'm sorry but I'm still having issues with the code on XCode 11.4. Here's what's happening. I downloaded the source code from Manning's website and it compiles. However, if I copy the code, create a new playground, paste the code in it and compile, it gives me some errors. This happens if I get the code and use it in any other playground or project.

I recorded to be more clear. Here's the link with the video: https://youtu.be/djc348BBoaI

Since it's exactly the same code, do you have any idea why is XCode complaining, except when I open the project from the code downloaded from Manning's website?

Thanks again,

Marcelo

**Comment by tjeerdintveen** [comment]
I'm sorry I never saw the notification for this issue. I'll have a look and get back to you with Xcode 12

**Comment by tjeerdintveen** [comment]
Okay I updated the source, I verified it on Xcode 12, should work now. I recommend reaching out to me via twitter @tjeerdintveen if you're stuck for a speedier reply. Sorry about that. Cheers!
